export enum ACTION_TYPES {
  SAVE_RESTAURANTS = "SAVE_RESTAURANTS",
  SAVE_RESTAURANT_PAGE = "SAVE_RESTAURANT_PAGE",
  SET_LOAD_RESTAURANTS_ERROR = "SET_LOAD_RESTAURANTS_ERROR",
  START_LOADING = "START_LOADING",
  STOP_LOADING = "STOP_LOADING",
  SET_ORDER = "SET_ORDER",
  SET_MODAL_WINDOW = "SET_MODAL_WINDOW",
  ADD_TO_CART = "ADD_TO_CART",
  CHANGE_AMOUNT = "CHANGE_AMOUNT",
  RETURN_CART = "RETURN_CART",
  CALCULATE_CART_TOTAL = "CALCULATE_CART_TOTAL",
}
